# Generated by Django 4.0.4 on 2022-05-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_answer_last_modifier_alter_answer_writer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='title',
            field=models.TextField(default='무제', verbose_name='제목'),
        ),
    ]
