# Generated by Django 4.0.4 on 2022-05-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_faq_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='state',
            field=models.CharField(choices=[('Register', '문의 등록'), ('Accept', '접수 완료'), ('Finish', '답변 완료')], default=('Register', '문의 등록'), max_length=256),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='title',
            field=models.CharField(default='무제', max_length=256, verbose_name='제목'),
        ),
    ]
